# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd4ef50fbbf244c46348accac249c097c2d5a48dc3251f5d54c6ffae49b093ee946be6a566d0daedaa992142233cefc6ad3cef1ba52a87fb7bda575bc361cf15

test:
  secret_key_base: 7b1bab20ed7d7d4ce441f06f8fb326af7eb7ed075c8a84c17717cb91a31d507b345bf13e6f57ee00c5c906fb9d9a646a22f841481bac5958c3ccb8244a659c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
